#!/usr/bin/env bash

readonly DOT_DIR="${HOME}/.dot"
readonly INSTALL_PREFIX="${HOME}/."

readonly TOOLS=$(find . -maxdepth 1 -mindepth 1 -type d -not -name ".*")

main() {
	echo "################################"
	echo "# Dot Uninstalling"
	echo "################################"

	platform_tools/uninstall

	for tool in ${TOOLS[@]}
	do
		${tool}/uninstall
	done
}

main $@
