#!/usr/bin/env bash

set -x

link_dotfiles() {
	local files=(tmux.conf)
	link -p "${INSTALL_PREFIX}" ${files[@]/#/-l }
}

install_tmux() {
        if pkgcheck tmux; then
		pkginstall tmux
	fi
}

main() {
	link_dotfiles
        install_tmux
}

main $@
