# neuralsandwich's zshenv

#############
# Set Paths #
#############

# Path
typeset -U path
path=(/usr/local/bin /opt/local/bin /usr/local/opt/go/libexec/bin $path[@])

## Application Path Additions
# tfenv
path=("$HOME/.tfenv/bin" $path[@])

# Go
path=("$HOME/.go/bin" $path[@])
path=("$HOME/go/bin" $path[@])

# Zsh Function Path
typeset -U fpath
fpath=($ZSH/func "${fpath[@]}")
fpath=($ZSH/func/battery/ "${fpath[@]}")
fpath=(/usr/share/zsh/site-function "${fpath[@]}")

# Vim key bindings
bindkey -v

# Dot File Localtions
ZSH="$HOME/.zsh"
DOTFILES="$HOME/.dot"

# Environment Variables
export EDITOR="vim"
export PAGER="less -i"
export VISUAL="$EDITOR"

# Zsh settings for history
export HISTIGNORE="&:ls:[bf]g:exit:reset:clear:cd:cd ..:cd.."
export HISTSIZE=25000
export HISTFILE="$HOME/.zsh_history"
export SAVEHIST=10000
bindkey '^R' history-incremental-search-backward

# GPG key
export GPGKEY="8A6C3D34"

# Debian package information
export DEBFULLNAME="Sean Jones"
export DEBEMAIL="neuralsandwich@gmail.com"

# Ccache Options
export CCACHE_DIR="$HOME/dev/.ccache"

# Application Environment Variables
export GOPATH=$HOME/go

# Local Config
# Sourced last as it needs to override
source "$DOTFILES/local/zshenv"
